pull_request_rules:
  - name: Automatic merge for Owner
    conditions:
      - status-success=stickler-ci
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/travis-ci/push
      - status-success=circleci-test
      - status-success=Shippable
      - author=matejkosiarcik
      - base=master
    actions:
      merge:
        method: merge
        strict: true
      delete_head_branch: {}
  - name: Automatic merge for dependabot
    conditions:
      - status-success=stickler-ci
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/travis-ci/push
      - status-success=circleci-test
      - status-success=Shippable
      - author=dependabot[bot]
      - base=master
    actions:
      merge:
        method: merge
        strict: true
      delete_head_branch: {}
