#
# This file is part of Stopwatch which is released under MIT license.
# See file LICENSE.txt or go to https://github.com/matejkosiarcik/Stopwatch for full license details.
#

---
extends: default

# exclude paths
ignore: |
    .build/
    .git/
    build/
    Carthage/
    fastlane/
    Packages/
    Pods/

# Rule customization
rules:
    line-length:
        max: 120
...
