#!/bin/sh
#
# This file is part of Stopwatch which is released under MIT license.
# See file LICENSE.txt or go to https://github.com/matejkosiarcik/Stopwatch for full license details.
#

# setup
set -euf
cd "$(dirname "${0}")/.."
. "./Utils/helpers.sh"

# SwiftPM
if check swift; then
    swift package resolve
    swift package generate-xcodeproj --enable-code-coverage --xcconfig-overrides "Config/Settings.xcconfig"
fi
