#!/bin/sh
#
# This file is part of Stopwatch which is released under MIT license.
# See file LICENSE.txt or go to https://github.com/matejkosiarcik/Stopwatch for full license details.
#

# setup
set -euf
cd "$(dirname "${0}")/.."
. "./Utils/helpers.sh"

# Sourcery
if check sourcery; then
    target="Tests/LinuxMain.swift"
    sourcery --sources Tests/ --templates Templates/Sourcery.LinuxMain.swift.stencil \
        --args testimports='@testable import cliTests
@testable import libTests' --output "${target}" >/dev/null
    strip "${target}"
fi
