#!/bin/sh
#
# This file is part of Stopwatch which is released under MIT license.
# See file LICENSE.txt or go to https://github.com/matejkosiarcik/Stopwatch for full license details.
#

set -euf
cd "$(dirname "${0}")/.."

# Sourcery
target="Tests/LinuxMain.swift"
sourcery --sources 'Tests/' --templates 'Templates/LinuxMain.swift.stencil' \
    --args testimports='@testable import CoreTests' --output "${target}" >'/dev/null'
printf '%s\n' "$(cat -s "${target}")" >"${target}"
