#!/bin/sh
#
# This file is part of Stopwatch which is released under MIT license.
# See file LICENSE.txt or go to https://github.com/matejkosiarcik/Stopwatch for full license details.
#

# setup
set -euf
cd "$(dirname "${0}")/.."
. "./Utils/helpers.sh"

# All files
if check git; then
    text_files | while IFS= read -r file; do
        strip "${file}"
    done
fi

# Swift
if check swiftlint; then
    swiftlint autocorrect 2>/dev/null
fi

# Shell
if check shfmt; then
    shell_files | while IFS= read -r file; do
        shfmt -i 4 -p -w "${file}"
    done
fi
