#!/bin/sh
#
# This file is part of Stopwatch which is released under MIT license.
# See file LICENSE.txt or go to https://github.com/matejkosiarcik/Stopwatch for full license details.
#

# setup
set -euf
cd "$(dirname "${0}")/.."
. "./Utils/helpers.sh"

# Swift
if check swiftlint; then
    swiftlint lint 2>/dev/null
fi

# Markdown
if check mdl; then
    mdl "." --git-recurse || true
fi

# Yaml
if check yamllint; then
    yamllint "." --format parsable --config-file ".yamllint.yml" || true
fi

# Shell
if check shellcheck; then
    shell_files | while IFS= read -r file; do
        shellcheck --external-sources "./Utils/helpers.sh" --format gcc "${file}" || true
    done
fi
if check shfmt; then
    shell_files | while IFS= read -r file; do
        shfmt -i 4 -p -l "${file}" \
            | sed -E "s~(.*)~\1: warning: file badly formatted, run 'format' script to resolve (bad_format)~"
    done
fi
# Invoke various shells with scripts for alternative linting via dry runs
if check sh; then
    shell_files | while IFS= read -r file; do
        sh -n "${file}" || true
    done
fi
if check bash; then
    shell_files | while IFS= read -r file; do
        bash -n "${file}" || true
        bash --posix -o pipefail -n "${file}" || true
        bash -o posix -o pipefail -n "${file}" || true
    done
fi
if check dash; then
    shell_files | while IFS= read -r file; do
        dash -n "${file}" || true
    done
fi
if check ksh; then
    shell_files | while IFS= read -r file; do
        ksh -n "${file}" || true
    done
fi
if check mksh; then
    shell_files | while IFS= read -r file; do
        mksh -n "${file}" || true
    done
fi
if check zsh; then
    shell_files | while IFS= read -r file; do
        zsh -n "${file}" || true
    done
fi
if check yash; then
    shell_files | while IFS= read -r file; do
        yash -n "${file}" || true
        yash --posix -n "${file}" || true
        yash -o posixly-correct -n "${file}" || true
    done
fi
