#!/bin/sh
#
# test
# Copyright © 2017 Matej Kosiarcik. All rights reserved.
# This file tests project
#

# setup
set -euf
cd "$(dirname "${0}")/.."
. "./Tools/helpers.sh"

# Run classic build
if [ "${#}" -eq "0" ]; then "./Tools/build"; else "./Tools/build" "${@}"; fi

# Swift
if check swift; then
    { if [ "${#}" -eq "0" ]; then swift test; else swift test "${@}"; fi; } 2>&1 \
        | tail -n 2
fi
