#!/bin/sh
#
# build
# Copyright © 2017 Matej Kosiarcik. All rights reserved.
# This file builds project
#

# setup
set -euf
cd "$(dirname "${0}")/.."
. ./Tools/helpers.sh

# Pre build stages
./Tools/prepare

# Swift compiler
if check swift; then
    { if [ "${#}" -eq "0" ]; then swift build; else swift build "${@}"; fi; } 2>/dev/null \
        | grep -Ev "^Compile " | grep -Ev "^Linking " || true
fi
