#!/bin/sh
#
# format
# Copyright © 2017 Matej Kosiarcik. All rights reserved.
# This file contains formatting procedures for project's source code
#

# setup
set -euf
cd "$(dirname "${0}")/.."

# All
# this removes duplicate empty lines and trailing newlines
strip() { printf "%s\n" "$(cat -s "${1}")" >"${1}"; }
git ls-tree -r --name-only "HEAD" | while IFS= read -r file; do
    strip "${file}"
done

# Swift
if command -v swiftlint >/dev/null 2>&1; then
    swiftlint autocorrect 2>/dev/null
else
    printf "%s\n" "warning: swiftlint not found. (tool_not_found)"
fi

# Shell
if command -v shfmt >/dev/null 2>&1; then
    find "./Tools" -type f -not -name "\.*" | while IFS= read -r file; do
        shfmt -i 4 -p -w "${file}"
    done
else
    printf "%s\n" "warning: shfmt OR xmllint not found. (tool_not_found)"
fi
