#!/bin/sh
#
# lint
# Copyright © 2017 Matej Kosiarcik. All rights reserved.
# This file contains lint procedures for project's source code
#

# setup
set -euf
cd "$(dirname "${0}")/.."

# Swift
if command -v swiftlint >/dev/null 2>&1; then
    swiftlint lint 2>/dev/null
else
    printf "%s\n" "warning: swiftlint not found. (tool_not_found)"
fi

# Markdown
if command -v mdl >/dev/null 2>&1; then
    mdl .
else
    printf "%s\n" "warning: markdownlint(mdl) not found. (tool_not_found)"
fi

# Yaml
if command -v yamllint >/dev/null 2>&1; then
    yamllint  -f parsable -c .yamllint.yml .
else
    printf "%s\n" "warning: yamllint not found. (tool_not_found)"
fi

# Shell
if command -v shellcheck >/dev/null 2>&1; then
    SHELL_FILES=$(find -E "./Tools" -type f | tr "\n" " ")
    # shellcheck disable=SC2086
    [ ! -z "${SHELL_FILES}" ] && shellcheck -f gcc ${SHELL_FILES}
else
    printf "%s\n" "warning: shellcheck not found. (tool_not_found)"
fi
