#!/bin/sh
#
# lint
# Copyright © 2017 Matej Kosiarcik. All rights reserved.
# This file contains lint procedures for project's source code
#

# setup
set -euf
cd "$(dirname "${0}")/.."

swiftlint lint 2>/dev/null
