#!/bin/sh
#
# prepare
# Copyright © 2017 Matej Kosiarcik. All rights reserved.
# This file runs before build
#

# setup
set -euf
cd "$(dirname "${0}")/.."

# Run this pre-build stages
./Tools/format
./Tools/lint
